import { ICost } from './CostService';

export const InitialCostState: ICost = {
  cod: '',
  name: '',
  unit: '',
  qt: '' as any,
  st: '',
  type: '',
  sf_st: '',
  id: '',
  materialsProduct: [],
  normalOperationsProduct: [],
  injectionOperationsProduct: [],
  totalMaterials: '' as any,
  totalNormalOperations: '' as any,
  totalInjectionOperations: '' as any,
  markUpProduct: '' as any,
  productInformations: '' as any,
  totalCost: '' as any,
  unitCost: '' as any,
  profitProduct: '' as any,
  realProfitProduct: '' as any,
  sugestedPrice: '' as any,
  mediumDiscount: '' as any,
};
